### ISSUE TITLE
We want to update this dataset regularly on daily basis 

### ISSUE THREAD

**Issue by Mikanebu** [datasets/s-and-p-500-companies-financials#3]
We want to update this dataset on regular basis, so it will be up to date.

## Acceptance criteria

* [ ] runs daily by Travis CI

## Tasks

* [ ] activate Travis CI, and setup crontab to `day`
* [ ] update travis.yml since it is broken

**Comment by olayway** [comment]
Fixed. The workflow that updates the data runs daily now.
